language: node_js
node_js: 
  - "11.10.1"
install:
  - npm install
before_script:
  - export COVERAGE_TOKEN=$COVERAGE_TOKEN
  - export HEROKU_TOKEN=$HEROKU_TOKEN
script:
  - npm run write-coveralls
  - npm test
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: cookwithme_BE
  on: master
  strategy: git